on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: sreesitcontainerreg.azurecr.io
        username: ${{ secrets.acr_sreesitcontainerreg_username }}
        password: ${{ secrets.acr_sreesitcontainerreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/helloWorld/hello-world-servlet-master/docker" -f  "helloWorld/hello-world-servlet-master/docker/Dockerfile" -t sreesitcontainerreg.azurecr.io/sreesit1ose:${{ github.sha }}
        docker push sreesitcontainerreg.azurecr.io/sreesit1ose:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_sreesit1ose_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep sreesit1oseaec5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace sreesit1oseaec5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: sreesit1oseaec5
        container-registry-url: sreesitcontainerreg.azurecr.io
        container-registry-username: ${{ secrets.acr_sreesitcontainerreg_username }}
        container-registry-password: ${{ secrets.acr_sreesitcontainerreg_password }}
        secret-name: sreesit1osedockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: sreesit1oseaec5
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          sreesitcontainerreg.azurecr.io/sreesit1ose:${{ github.sha }}
        imagepullsecrets: |
          sreesit1osedockerauth